// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5S1s9V8yCZvFMCEzotgGzzwXTBtXzIhU',
    appId: '1:159135395904:web:b4cfbd4c219068597fefa5',
    messagingSenderId: '159135395904',
    projectId: 'disaster-management-8442b',
    authDomain: 'disaster-management-8442b.firebaseapp.com',
    storageBucket: 'disaster-management-8442b.firebasestorage.app',
    measurementId: 'G-LFQ305N56W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_ADzWB3A-_US0aBKIHRQ3qvAWcYtgRXg',
    appId: '1:159135395904:android:bb6df3a95e39ef797fefa5',
    messagingSenderId: '159135395904',
    projectId: 'disaster-management-8442b',
    storageBucket: 'disaster-management-8442b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZUfE1TnNcaBDfOj-DsCPtKOR7MZclxzM',
    appId: '1:159135395904:ios:ba59810f92f3b8ce7fefa5',
    messagingSenderId: '159135395904',
    projectId: 'disaster-management-8442b',
    storageBucket: 'disaster-management-8442b.firebasestorage.app',
    iosBundleId: 'com.example.disasterManagement',
  );
}
