// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBtDvttzFNp_q5BF3vadbBtiDdBO6bYKWY',
    appId: '1:454228069096:web:7b059edce0658f7ba6975d',
    messagingSenderId: '454228069096',
    projectId: 'student-management-bb597',
    authDomain: 'student-management-bb597.firebaseapp.com',
    storageBucket: 'student-management-bb597.appspot.com',
    measurementId: 'G-VGBRTPFXBS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8LfB53-0b6RdTOl8jNVXQmehoeZk0hss',
    appId: '1:454228069096:android:7cdc0575649a606fa6975d',
    messagingSenderId: '454228069096',
    projectId: 'student-management-bb597',
    storageBucket: 'student-management-bb597.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhkxcSygY3FqMTtSQy5-RjdWz9We1TzCA',
    appId: '1:454228069096:ios:dc029a4e1f1bf3d9a6975d',
    messagingSenderId: '454228069096',
    projectId: 'student-management-bb597',
    storageBucket: 'student-management-bb597.appspot.com',
    iosBundleId: 'com.example.disasterManagement',
  );

}